"""Initial migration

Revision ID: 943231068777
Revises: 
Create Date: 2025-12-25 06:18:39.124228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943231068777'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegates',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('ens_name', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_delegates_address'), 'delegates', ['address'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_signal', sa.Boolean(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delegate_address', sa.String(), nullable=True),
    sa.Column('proposal_id', sa.String(), nullable=True),
    sa.Column('choice', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegate_address'], ['delegates.address'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_delegates_address'), table_name='delegates')
    op.drop_table('delegates')
    # ### end Alembic commands ###
