"""
Participation Architecture - Main CLI Entry Point
"""

import argparse
import json
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

from collector import SnapshotCollector
from analysis import BehavioralAnalyzer


def collect_command(args):
    """Handle data collection"""
    print(f"🔄 Collecting data from {args.space}...")
    
    collector = SnapshotCollector(space_id=args.space)
    data = collector.collect_full_dataset(num_proposals=args.proposals)
    collector.save_to_cache(data)
    
    print(f"✅ Collection complete!")


def analyze_command(args):
    """Handle analysis"""
    print("📊 Running behavioral analysis...")
    
    # Load data
    collector = SnapshotCollector(space_id=args.space)
    data = collector.load_from_cache()
    
    if not data:
        print("❌ No cached data found. Run 'collect' command first.")
        return
    
    # Analyze
    analyzer = BehavioralAnalyzer(data)
    results = analyzer.analyze_all_delegates()
    health = analyzer.get_health_summary()
    
    # Display results
    print("\n" + "="*60)
    print("DAO HEALTH SUMMARY")
    print("="*60)
    for key, value in health.items():
        print(f"{key.replace('_', ' ').title()}: {value}")
    
    print("\n" + "="*60)
    print("TOP 10 AT-RISK DELEGATES (Highest Fatigue)")
    print("="*60)
    print(results.head(10).to_string(index=False))
    
    # Save to file
    if args.output:
        output_path = Path(args.output)
        results.to_json(output_path, orient="records", indent=2)
        print(f"\n✅ Full results saved to {output_path}")
        
        # Save summary
        summary_path = output_path.parent / "health_summary.json"
        with open(summary_path, 'w') as f:
            json.dump(health, f, indent=2)
        print(f"✅ Summary saved to {summary_path}")


def report_command(args):
    """Generate formatted report"""
    print("📝 Generating report...")
    
    collector = SnapshotCollector(space_id=args.space)
    data = collector.load_from_cache()
    
    if not data:
        print("❌ No cached data found. Run 'collect' command first.")
        return
    
    analyzer = BehavioralAnalyzer(data)
    results = analyzer.analyze_all_delegates()
    health = analyzer.get_health_summary()
    
    # Generate markdown report
    report = f"""# Participation Architecture Report
**Space:** {data['space']}  
**Generated:** {data['collected_at']}  
**Proposals Analyzed:** {len(data['proposals'])}

## Executive Summary

- **Total Delegates:** {health['total_delegates']}
- **Average 30-Day Participation:** {health['avg_participation_30d']:.1%}
- **Average Fatigue Score:** {health['avg_fatigue_score']}/100
- **At-Risk Delegates:** {health['at_risk_delegates']} ({health['at_risk_delegates']/health['total_delegates']:.1%})
- **Active Delegates:** {health['active_delegates']} ({health['active_delegates']/health['total_delegates']:.1%})

## Key Findings

### High-Risk Delegates (Fatigue > 60)
{results[results['fatigue_score'] > 60][['delegate', 'fatigue_score', 'longest_break_days', 'trend']].to_markdown(index=False)}

### Most Active Delegates (Top 10)
{results.nlargest(10, 'participation_30d')[['delegate', 'participation_30d', 'participation_90d', 'total_votes']].to_markdown(index=False)}

## Methodology

This analysis uses Self-Determination Theory (SDT) to identify patterns of delegate fatigue:
- **Participation Rate:** Percentage of proposals voted on in 30/90 day windows
- **Fatigue Index:** Composite score based on voting gaps, burnout patterns, and trends
- **Burnout Detection:** Identifies rapid voting followed by extended inactivity

---
*Generated by Participation Architecture v0.1*
"""
    
    output_path = Path(args.output)
    output_path.write_text(report)
    print(f"✅ Report saved to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Participation Architecture - Delegate Fatigue Analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Collect command
    collect_parser = subparsers.add_parser("collect", help="Fetch data from Snapshot")
    collect_parser.add_argument(
        "--space",
        default="arbitrumfoundation.eth",
        help="Snapshot space ID"
    )
    collect_parser.add_argument(
        "--proposals",
        type=int,
        default=50,
        help="Number of proposals to fetch"
    )
    
    # Analyze command
    analyze_parser = subparsers.add_parser("analyze", help="Run behavioral analysis")
    analyze_parser.add_argument(
        "--space",
        default="arbitrumfoundation.eth",
        help="Snapshot space ID"
    )
    analyze_parser.add_argument(
        "--output",
        default="data/results.json",
        help="Output file path"
    )
    
    # Report command
    report_parser = subparsers.add_parser("report", help="Generate markdown report")
    report_parser.add_argument(
        "--space",
        default="arbitrumfoundation.eth",
        help="Snapshot space ID"
    )
    report_parser.add_argument(
        "--output",
        default="data/report.md",
        help="Output file path"
    )
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return
    
    # Route to appropriate command
    if args.command == "collect":
        collect_command(args)
    elif args.command == "analyze":
        analyze_command(args)
    elif args.command == "report":
        report_command(args)


if __name__ == "__main__":
    main()
